Factory/Models/Machine.cs
using System;
using System.Collections.Generic;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }
    public string Name { get; set; }
    public string Description { get; set; }
    public int MachineId { get; set; }

    public virtual ICollection<EngineerMachine> JoinEntities { get; set; }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Factory.Models;
using System.Linq;
using System;


namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Machine> orderedList = _db.Machines.OrderBy(machine => machine.Name).ToList();
      return View(orderedList);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

        public ActionResult Details(int id)
    {
      Machine thisMachine = _db.Machines
      .Include(machine => machine.JoinEntities)
      .ThenInclude(join => join.Engineer)
      .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine, int EngineerId)
    {
      if (EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId,  MachineId = machine.MachineId });
      }
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddEngineer(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int EngineerId)
    {
      if (EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }
    
    [HttpPost]
    public ActionResult DeleteEngineer(int joinId)
    {
      EngineerMachine joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add a coures</h2>

<div class="margin center">
  <h4>Add a engineer to this machine: @Html.DisplayFor(model => model.Name)</h4>
  @using (Html.BeginForm())
  {
      @Html.HiddenFor(model => model.MachineId)

      @Html.Label("Select engineer")
      @Html.DropDownList("EngineerId")

      <input type="submit" value="Save" />
  }
</div>

<div class="center">
  <p>@Html.ActionLink("Back to list", "Index")</p>
</div>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add new machines to the registry</h2>

<div class="margin">
  @using (Html.BeginForm())
  {
    <div class="form-group">
      <div class="form-control">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name)
      </div>
      <div class="form-control">
        @Html.LabelFor(model => model.Description)
        @Html.TextBoxFor(model => model.Description)
      </div>
      <input class="btn btn-info" type="submit" value="Add new machine"/>
    </div>
  }
</div>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Are you sure you want to delete this machine?</h2>
<div class="margin center">
  @Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
  @using (Html.BeginForm())
  {
      <input clas="btn btn-danger" type="submit" value="Delete" />
  }
</div>
<div class="center">
  <p>@Html.ActionLink("Back to List", "Index")</p>
</div>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine;

<h2>Machine Details</h2>
<hr />
<h4>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h4>
<h6>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)<h6>

<div class="margin">
  @if(@Model.JoinEntities.Count == 0)
  {
    <p>No engineers are licenced to operate on this machine</p>
  }
  else
  {
    <h4>Current engineers licenced to repair this machine</h4>
    <div class="row">
      @foreach(var join in Model.JoinEntities)
      {
        <div class="col">
          <h5>Name: @join.Engineer.Name</h5>
          <p>Date Employed: @join.Engineer.DateEmployed</p>
          @using (Html.BeginForm("DeleteEngineer", "Machines"))
          {
            @Html.Hidden("joinId", @join.EngineerMachineId)
            <input class="btn btn-danger" type="submit" value="Delete"/>
          }
        </div>
      }
    </div>
  }
</div>

<div class="margin center">
  <p>@Html.ActionLink("Edit Machine details", "Edit", new { id = Model.MachineId })</p>
  <p>@Html.ActionLink("Remove machine from registry", "Delete", new { id = Model.MachineId })</p>
  <p>@Html.ActionLink("Add a Engineer", "AddEngineer", new { id = Model.MachineId })</p>
</div>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Edit Machine: @Model.Name</h2>

<div class="margin">
  @using (Html.BeginForm())
  {
    @Html.Hidden("MachineId", Model.MachineId)
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name, new { placeholder="${Model.Name}" })

    @Html.LabelFor(model => model.Description)
    @Html.TextBoxFor(model => model.Description, new { placeholder="${Model.Description}" })

    @Html.Label("Select Engineers")
    @Html.DropDownList("EngineerId")
    <input type="submit" value="Update Machine"/>
  }
</div>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Machine>;

<h2>Machine registry</h2>

<div class="margin center row">
  @if (@Model.Count == 0)
  {
    <h3>No machines have been added to the registry</h3>
  }
  @foreach (Machine machine in Model)
  {
    <div class="col">
      <h4>@Html.ActionLink($"{machine.Name}", "Details", new { id = machine.MachineId })</h4>
      <h6>Description: @machine.Description</h6>
    </div>
  }
</div>

<div class="center">
  <p>@Html.ActionLink("Add new machine", "Create")</p>
</div>