Factory/Models/Engineer.cs
using System;
using System.Collections.Generic;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }
    public string Name { get; set; }
    public DateTime DateEmployed { get; set; }
    public int EngineerId { get; set; }

    public virtual ICollection<EngineerMachine> JoinEntities { get; set; }
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Factory.Models;
using System.Linq;
using System;


namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Engineer> query = _db.Engineers.OrderBy(engineer => engineer.Name).ToList();
      return View(query);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int machineId)
    {
      if (machineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = machineId, EngineerId = engineer.EngineerId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      EngineerMachine joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Engineer thisEngineer = _db.Engineers
        .Include(engineer => engineer.JoinEntities)
        .ThenInclude(join => join.Machine)
        .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Edit(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId,  EngineerId = engineer.EngineerId });
      }
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Add a machine</h2>

<div class="margin">
  <h4>Add a machine to this engineer: @Html.DisplayFor(model => model.Name)</h4>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.EngineerId)

    @Html.Label("Select machine")
    @Html.DropDownList("MachineId")

    <input type="submit" value="Save" />
  }
</div>
<div class="center">
  <p>@Html.ActionLink("Back to list", "Index")</p>
</div>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Add new engineers to the registry</h2>

<div class="margin">
  @using (Html.BeginForm())
  {
    <div class="form-group">
      <div class="form-control">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name)
      </div>
      <div class="form-control">
        @Html.LabelFor(model => model.DateEmployed)
        @Html.TextBoxFor(model => model.DateEmployed, new { type="date" })
      </div>
      <input class="btn btn-info" type="submit" value="Add new engineer"/>
    </div>
  }
</div>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Are you sure you want to delete this engineer from the registry?</h2>

<div class="margin">
  @Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
  @using (Html.BeginForm())
  {
    <input class="btn btn-danger" type="submit" value="Delete" />
  }
</div>
<div class="center">
  <p>@Html.ActionLink("Back to List", "Index")</p>
</div>

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer;

<h2>Engineer Details</h2>
<hr />
<h4>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h4>
<h6>@Html.DisplayNameFor(model => model.DateEmployed): @Html.DisplayFor(model => model.DateEmployed)<h6>

<div class="margin">
  @if(@Model.JoinEntities.Count == 0)
  {
    <p>This Engineer certified to operate any machines yet</p>
  }
  else
  {
    <h4>Current machines the engineer is licenced to operate:</h4>
    <div class="row">
      @foreach(var join in Model.JoinEntities)
      {
        <div class="col">
          <h5>Name: @join.Machine.Name</h5>
          <h6>Description: @join.Machine.Description</h6>
          @using (Html.BeginForm("DeleteMachine", "Engineers"))
          {
            @Html.Hidden("joinId", @join.EngineerMachineId)
            <input class="btn btn-danger" type="submit" value="Delete"/>
          }
        </div>
      }
    </div>
  }
</div>

<div class="margin center">
  <p>@Html.ActionLink("Edit Engineer details", "Edit", new { id = Model.EngineerId })</p>
  <p>@Html.ActionLink("Remove engineer from registry", "Delete", new { id = Model.EngineerId })</p>
  <p>@Html.ActionLink("Add a Machine", "AddMachine", new { id = Model.EngineerId })</p>
</div>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Edit engineer: @Model.Name</h2>

<div class="margin">
  @using (Html.BeginForm())
  {
    <div class="form=group">
      <div class="form-control">
        @Html.Hidden("EngineerId", Model.EngineerId)
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name, new { placeholder="${Model.Name}" })
      </div>
      <div class="form-control">
        @Html.LabelFor(model => model.DateEmployed)
        @Html.TextBoxFor(model => model.DateEmployed, new { type="date", placeholder="${Model.DateEmployed}" })
      </div>
      <div class="form-control">
        @Html.Label("Select Machines")
        @Html.DropDownList("MachineId")
      </div>
    </div>
    <input type="submit" value="Update engineer details"/>
  }
</div>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Engineer>;

<h2>Engineer registry</h2>

<div class="margin center row">
  @if (@Model.Count == 0)
  {
    <h3>No engineers have been added to the registry</h3>
  }
  @foreach (Engineer engineer in Model)
  {
    <div class="col">
      <h4>@Html.ActionLink($"{engineer.Name}", "Details", new { id = engineer.EngineerId })</h4>
      <h6>Description: @engineer.DateEmployed</h6>
    </div>
  }
  
</div>
<div class="center">
  <p>@Html.ActionLink("Add new engineer", "create")</p>
</div>